import { describe, expect, it } from "vitest";
import handler from "../api/render-svg";
import { DEFAULT_EXPORT_PREAMBLE } from "../src/renderer/document";

describe("render-svg api", () => {
  it("returns a successful SVG payload", async () => {
    const request = {
      method: "POST",
      body: JSON.stringify({
        code: String.raw`\begin{quantikz}
\lstick{$\ket{0}$} & \gate{H} & \ctrl{1} & \meter{} \\
\lstick{$\ket{0}$} & \qw & \targ{} & \qw
\end{quantikz}`,
        preamble: DEFAULT_EXPORT_PREAMBLE
      }),
      on: () => request
    };

    const responseState: { statusCode?: number; payload?: unknown } = {};
    const response = {
      status(code: number) {
        responseState.statusCode = code;
        return this;
      },
      json(payload: unknown) {
        responseState.payload = payload;
        return this;
      }
    };

    await handler(request, response);

    expect(responseState.statusCode).toBe(200);
    expect(responseState.payload).toMatchObject({
      success: true
    });

    const payload = responseState.payload as { svg?: string };
    expect(payload.svg).toContain("<?xml version=");
    expect(payload.svg).toContain("<svg");
    expect(payload.svg).toContain("generated by dvisvgm");
  });
});
