import { describe, expect, it } from "vitest";
import { DEFAULT_EXPORT_PREAMBLE } from "../src/renderer/document";
import { renderQuantikzSvg } from "../src/server/renderQuantikz";

describe("renderQuantikzSvg", () => {
  it("returns SVG markup for a quantikz circuit", async () => {
    const code = String.raw`\begin{quantikz}
\lstick{$\ket{0}$} & \gate{H} & \ctrl{1} & \meter{} \\
\lstick{$\ket{0}$} & \qw & \targ{} & \qw
\end{quantikz}`;

    const result = await renderQuantikzSvg(code, DEFAULT_EXPORT_PREAMBLE);

    expect(result.success).toBe(true);
    expect(result.error).toBeUndefined();
    expect(result.svg).toContain("<?xml version=");
    expect(result.svg).toContain("<svg");
    expect(result.svg).toContain("generated by dvisvgm");

    const parsed = new DOMParser().parseFromString(result.svg ?? "", "image/svg+xml");
    expect(parsed.querySelector("parsererror")).toBeNull();
    expect(parsed.querySelector("svg")?.getAttribute("viewBox")).toBeTruthy();
    expect(parsed.querySelectorAll("path").length).toBeGreaterThan(0);
    expect(parsed.querySelectorAll("use").length).toBeGreaterThan(0);
  });
});
