#!/usr/bin/env python3
r'''Best-effort Quantikz -> plain TikZ transpiler.

Preferred deployment option on a server with only TikZ:
ship `tikzlibraryquantikz2.code.tex` next to your document and load it with
`\usetikzlibrary{quantikz2}`. This script is for cases where you want a rough
transpile to ordinary TikZ primitives.

Supported subset: \gate, \phase, \meter, \ctrl, \control, \targ, \targX,
\swap, \lstick, \rstick, \setwiretype, blank cells, and global
`[wire types={...}]`.
'''
from __future__ import annotations
import argparse, re, sys
from dataclasses import dataclass, field
from typing import List, Optional, Tuple

@dataclass
class Cell:
    raw: str
    commands: List[Tuple[str, dict]] = field(default_factory=list)
    unsupported: List[str] = field(default_factory=list)
    wire_override: Optional[str] = None

@dataclass
class Circuit:
    rows: List[List[Cell]]
    wire_types: List[str]


def extract_env(src: str) -> Tuple[str, str]:
    m = re.search(r"\\begin\{quantikz\}(\[[^\]]*\])?(.*?)\\end\{quantikz\}", src, re.S)
    if not m:
        raise SystemExit("No quantikz environment found")
    return (m.group(1) or ""), m.group(2)


def parse_wire_types(opts: str) -> List[str]:
    m = re.search(r"wire\s*types\s*=\s*\{([^}]*)\}", opts)
    if not m:
        return []
    return [x.strip() for x in m.group(1).split(',') if x.strip()]


def split_rows(body: str) -> List[str]:
    body = re.sub(r"%.*", "", body)
    lines = [ln.rstrip() for ln in body.splitlines()]
    text = "\n".join(lines)
    rows = re.split(r"\\\\\s*\n?|\\\\", text)
    return [r.strip() for r in rows if r.strip()]


def split_cells(row: str) -> List[str]:
    # Quantikz examples overwhelmingly use plain matrix cells, so a simple split works well.
    return [c.strip() for c in row.split('&')]


def parse_cmds(cell_text: str) -> Cell:
    cell = Cell(raw=cell_text)
    s = cell_text.strip()
    if not s:
        return cell
    token_re = re.compile(
        r"\\(?P<name>gate|phase|meter|ctrl|control|targX|targ|swap|lstick|rstick|setwiretype)"
        r"(?:\[(?P<opt>[^\]]*)\])?"
        r"(?:\{(?P<arg>[^{}]*)\})?"
    )
    pos = 0
    for m in token_re.finditer(s):
        if m.start() > pos and s[pos:m.start()].strip():
            cell.unsupported.append(s[pos:m.start()].strip())
        name = m.group('name')
        opt = (m.group('opt') or '').strip()
        arg = (m.group('arg') or '').strip()
        if name == 'setwiretype':
            cell.wire_override = arg or 'q'
        else:
            cell.commands.append((name, {'opt': opt, 'arg': arg}))
        pos = m.end()
    if pos < len(s) and s[pos:].strip():
        cell.unsupported.append(s[pos:].strip())
    return cell


def parse_circuit(src: str) -> Circuit:
    opts, body = extract_env(src)
    rows_raw = split_rows(body)
    rows = [[parse_cmds(c) for c in split_cells(r)] for r in rows_raw]
    width = max((len(r) for r in rows), default=0)
    for r in rows:
        r += [Cell(raw='')] * (width - len(r))
    wire_types = parse_wire_types(opts)
    while len(wire_types) < len(rows):
        wire_types.append('q')
    return Circuit(rows, wire_types)


def seg(x1: float, y: float, x2: float, w: str) -> str:
    if w == 'n':
        return '% no wire'
    if w == 'c':
        return f"\\draw[densely double] ({x1},{y}) -- ({x2},{y});"
    if w == 'b':
        return f"\\draw[line width=1.2pt] ({x1},{y}) -- ({x2},{y});"
    return f"\\draw ({x1},{y}) -- ({x2},{y});"


def emit(c: Circuit) -> str:
    rows = len(c.rows)
    cols = len(c.rows[0]) if rows else 0
    out = []
    out.append('% Generated by quantikz_to_tikz.py')
    out.append('% Requires only \\usepackage{tikz}')
    out.append('\\begin{tikzpicture}[x=1.4cm,y=1.0cm,baseline=(current bounding box.center)]')
    out.append('  \\tikzset{qgate/.style={draw,minimum width=8mm,minimum height=6mm,inner sep=1pt},')
    out.append('            meter/.style={draw,minimum width=7mm,minimum height=6mm,inner sep=1pt},')
    out.append('            phase/.style={circle,fill,inner sep=1.4pt},')
    out.append('            oplus/.style={circle,draw,inner sep=0pt,minimum size=4.5mm}}')

    # horizontal wires; setwiretype in cell j changes the segment entering j
    for r in range(rows):
        wcur = c.wire_types[r]
        y = -r
        for j in range(cols):
            cell = c.rows[r][j]
            if j > 0:
                if cell.wire_override:
                    wcur = cell.wire_override
                out.append('  ' + seg(j - 1 + 0.15, y, j - 0.15, wcur))

    for r, row in enumerate(c.rows):
        y = -r
        for j, cell in enumerate(row):
            x = j
            for u in cell.unsupported:
                out.append(f'  % unsupported in cell ({r+1},{j+1}): {u}')
            for name, args in cell.commands:
                opt, arg = args['opt'], args['arg']
                if name == 'gate':
                    span = 1
                    m = re.match(r'\s*(-?\d+)', opt)
                    if m:
                        span = max(1, abs(int(m.group(1))))
                    out.append(f'  \\node[qgate,minimum height={max(0.55, span - 0.15):.2f}cm] at ({x},{y}) {{$ {arg} $}};')
                elif name == 'phase':
                    out.append(f'  \\node[phase] at ({x},{y}) {{}};')
                    if arg:
                        out.append(f'  \\node[above right=1pt] at ({x},{y}) {{$ {arg} $}};')
                elif name == 'meter':
                    out.append(f'  \\node[meter] at ({x},{y}) {{$\\mathrm{{M}}$}};')
                elif name == 'ctrl':
                    d = int(arg or '0')
                    out.append(f'  \\fill ({x},{y}) circle (1.6pt);')
                    out.append(f'  \\draw ({x},{y}) -- ({x},{y-d});')
                elif name == 'control':
                    out.append(f'  \\draw ({x},{y}) circle (2pt);')
                elif name == 'targ':
                    out.append(f'  \\node[oplus] at ({x},{y}) {{}};')
                elif name == 'targX':
                    out.append(f'  \\draw ({x-0.14},{y-0.14}) -- ({x+0.14},{y+0.14});')
                    out.append(f'  \\draw ({x-0.14},{y+0.14}) -- ({x+0.14},{y-0.14});')
                elif name == 'swap':
                    d = int(arg or '0')
                    out.append(f'  \\draw ({x-0.14},{y-0.14}) -- ({x+0.14},{y+0.14});')
                    out.append(f'  \\draw ({x-0.14},{y+0.14}) -- ({x+0.14},{y-0.14});')
                    out.append(f'  \\draw ({x},{y}) -- ({x},{y-d});')
                elif name == 'lstick':
                    out.append(f'  \\node[left] at ({x-0.35},{y}) {{{arg}}};')
                elif name == 'rstick':
                    out.append(f'  \\node[right] at ({x+0.35},{y}) {{{arg}}};')
    out.append('\\end{tikzpicture}')
    return '\n'.join(out) + '\n'


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('input', nargs='?')
    ap.add_argument('--stdin', action='store_true')
    ns = ap.parse_args()
    src = sys.stdin.read() if ns.stdin else open(ns.input, encoding='utf-8').read()
    sys.stdout.write(emit(parse_circuit(src)))
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
